server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    conversions:
      path: /conversions/**
      url: http://localhost:8080

spring:
  cloud:
    config:
      name: gateway
      discovery:
        service-id: config
        enabled: true
