server:
  port: 8083
management:
  context-path: /manage
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://xmlconv-registry:8761/eureka/
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    appname: xmlconv-qa
    # This needs to be able to be resolved by other services
    hostname: xmlconv-qa
spring:
  application:
    name: xmlconv-qa