server:
  port: 8080
  context-parameters:
    edu.yale.its.tp.cas.client.filter.loginUrl: https://sso.eionet.europa.eu/login
management:
  port: 8081
#  context-path: /manage
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    appname: xmlconv