management:
  port: 8081

eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#      statusPageUrlPath: http://${eureka.hostname}/info
#      healthCheckUrlPath: http://${eureka.hostname}/health

netflix:
  metrics:
    restClient:
      metricName: rest
