server:
    port: 8761
eureka:
  instance:
    hostname: localhost
    appname: xmlconv-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49
